version: '3'

services:
  zammad:
    depends_on:
      - elasticsearch
      - postgres
    image: computersciencehouse/zammad
    build: ./images/zammad
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOSTNAME=postgres
      - DB_NAME=zammad
      - DB_USERNAME=postgres
      - DB_PASSWORD=thisisntverysecure
      - ES_HOSTNAME=elasticsearch
    volumes:
      - zammad-data:/opt/zammad/storage

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=thisisntverysecure

  elasticsearch:
    image: computersciencehouse/zammad-elasticsearch
    build: ./images/elasticsearch
    restart: always
    volumes:
      - zammad-elasticsearch:/usr/share/elasticsearch/data

volumes:
  public:
  zammad-data:
    driver: local
  zammad-elasticsearch:
    driver: local
